### PR TITLE
dev-v0.6

### PR DESCRIPTION
**Pull request by ghost**
There's still a mysterious linker error:

```
[2/2] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/x86_64/libmonerujo.so
...
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)                           
  ninja: build stopped: subcommand failed.    
```

### CODE REVIEW

**Comment by ghost** [comment]
The linker error has nothing to do with randomx, since dev-v0.6 branch also triggers it.

**Comment by ghost** [comment]
complete error:

```
  ../../../../../external-libs/monero/lib/arm64-v8a/libwallet.a(wallet2.cpp.o): In function `std::__ndk1::__function::__func<net::socks::connector, std::__ndk1::allocator<net::socks::connector>, boost::unique_future<boost::asio::basic_stream_socket<boost::asio::ip::tcp> > (std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, boost::asio::basic_waitable_timer<std::__ndk1::chrono::steady_clock, boost::asio::wait_traits<std::__ndk1::chrono::steady_clock> >&)>::operator()(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, boost::asio::basic_waitable_timer<std::__ndk1::chrono::steady_clock, boost::asio::wait_traits<std::__ndk1::chrono::steady_clock> >&)':
  wallet2.cpp:(.text._ZNSt6__ndk110__function6__funcIN3net5socks9connectorENS_9allocatorIS4_EEFN5boost13unique_futureINS7_4asio19basic_stream_socketINS9_2ip3tcpEEEEERKNS_12basic_stringIcNS_11char_traitsIcEENS5_IcEEEESL_RNS9_20basic_waitable_timerINS_6chrono12steady_clockENS9_11wait_traitsISO_EEEEEEclESL_SL_SS_[_ZNSt6__ndk110__function6__funcIN3net5socks9connectorENS_9allocatorIS4_EEFN5boost13unique_futureINS7_4asio19basic_stream_socketINS9_2ip3tcpEEEEERKNS_12basic_stringIcNS_11char_traitsIcEENS5_IcEEEESL_RNS9_20basic_waitable_timerINS_6chrono12steady_clockENS9_11wait_traitsISO_EEEEEEclESL_SL_SS_]+0x4): undefined reference to `net::socks::connector::operator()(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, boost::asio::basic_waitable_timer<std::__ndk1::chrono::steady_clock, boost::asio::wait_traits<std::__ndk1::chrono::steady_clock> >&) const'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.
```

**Comment by ghost** [comment]
I'm trying to use git bisect to find the commit that breaks it, somewhere between dev-v0.6 and 6e093aa

File: script/build-external-libs/fetch-wownero.sh [hunk 1]
```diff
@@ -10,10 +10,10 @@ cd $EXTERNAL_LIBS_BUILD_ROOT
...
 
 # url="$base_dir/vendor/wownero"
-url="https://github.com/wownero/wownero"
-# url="https://github.com/wowario/wownero"
-version="v0.5.0.2"
-# version="1b5cefa"
+# url="https://github.com/wownero/wownero"
+url="https://github.com/wowario/wownero"
+# version="v0.5.1.0"
+version="a7845ab"
```
Comment (ghost) [inline script/build-external-libs/fetch-wownero.sh]: current commit is `1a54e7b`

File: script/build-external-libs/fetch-wownero.sh [hunk 2]
```diff
@@ -10,10 +10,10 @@ cd $EXTERNAL_LIBS_BUILD_ROOT
 
 
 # url="$base_dir/vendor/wownero"
-url="https://github.com/wownero/wownero"
-# url="https://github.com/wowario/wownero"
-version="v0.5.0.2"
-# version="1b5cefa"
+# url="https://github.com/wownero/wownero"
+url="https://github.com/wowario/wownero"
+# version="v0.5.1.0"
```
Comment (ghost) [inline script/build-external-libs/fetch-wownero.sh]: v0.6.0.0

File: script/build-external-libs/fetch-wownero.sh (hunk 1 above)
Comment (ghost) [reply script/build-external-libs/fetch-wownero.sh]: Yes, I'm testing different commits locally with a local repo. I think I found the problem, still building.

**Comment by ghost** [comment]
Linker error fixed by adding libnet to app/CMakelists

File: script/build-external-libs/fetch-wownero.sh (hunk 2 above)
Comment (ghost) [reply script/build-external-libs/fetch-wownero.sh]: Will use the tagged version in a later update

**Review by ghost — APPROVED** [review]
looks good, great job!
